### PR TITLE
do not leak LB when ingress class is changed

### LINKED ISSUE #481: Ingress-GCE does not GC LB resources when ingress class changed and no other ingress on GCE exists
Repro steps:
1. Make sure there is no ingress exists in the cluster.
2. Create a test ingress with no ingress class annotation
3. Wait for ingress-gce controller to provision LB
4. Add a non-GCE ingress class on the test ingress
5. The LB resources will be leaked. 

Root cause:
- Ingress-gce controller does not act on non-relevant ingresses.  https://github.com/kubernetes/ingress-gce/blob/release-1.3/pkg/controller/controller.go#L127
- Ingress-gce controller only GC resources in the ingress sync loop.
https://github.com/kubernetes/ingress-gce/blob/release-1.3/pkg/controller/controller.go#L287

### PR DESCRIPTION
**Pull request by pondohva**
This PR fixes #481

### CODE REVIEW

**Comment by pondohva** [comment]
I signed it

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -456,6 +462,17 @@ func (lbc *LoadBalancerController) sync(key string) error {
 	}
 	ing = ing.DeepCopy()
 
+	if !utils.IsGLBCIngress(ing) {
+		glog.V(2).Infof("Ingress %q class was changed, triggering GC", key)
```
Comment (rramkumar1) [inline pkg/controller/controller.go]: Can you explain this? 

We shouldn't delete the Ingress even though the class changed.

Comment (pondohva) [reply pkg/controller/controller.go]: We need to delete it from gcState.lbNames to allow GC delete load balancer.
I can just fix gcState and not delete it from Store.

Comment (rramkumar1) [reply pkg/controller/controller.go]: Yea, removing it from the gcState.lbNames sounds better.

We for sure do not want to delete it outright because this will affect other controllers that expect this ingress to exist.

Comment (pondohva) [reply pkg/controller/controller.go]: Fixed

**Comment by rramkumar1** [comment]
@pondohva Sorry for the delay. I will try to have another review by EOD

**Comment by rramkumar1** [comment]
@pondohva This looks good to me. Can you please add a unit test?

File: pkg/controller/controller.go [hunk 2]
```diff
@@ -456,6 +463,13 @@ func (lbc *LoadBalancerController) sync(key string) error {
...
+		// Remove lb from state for GC
+		gcState.lbNames = slice.RemoveString(gcState.lbNames, key, nil)
+		return lbc.ingSyncer.GC(gcState)
```
Comment (rramkumar1) [inline pkg/controller/controller.go]: Actually one comment here. I don't like that we have to call ingSyncer.GC() twice in this function.

Can you wrap the GC() call in line 491 into a separate function and then call that function here and in line 491?

Comment (pondohva) [reply pkg/controller/controller.go]: Check please

**Comment by pondohva** [comment]
@rramkumar1 could you please check test and wrapper function?

File: pkg/controller/controller.go [hunk 3]
```diff
@@ -153,6 +154,12 @@ func NewLoadBalancerController(
 		UpdateFunc: func(old, cur interface{}) {
 			curIng := cur.(*extensions.Ingress)
 			if !utils.IsGLBCIngress(curIng) {
+				oldIng := old.(*extensions.Ingress)
```
Comment (rramkumar1) [inline pkg/controller/controller.go]: Nit: Add a comment indicating the purpose of why we are enqueueing here.

File: pkg/controller/controller.go [hunk 4]
```diff
@@ -456,6 +463,13 @@ func (lbc *LoadBalancerController) sync(key string) error {
 	}
 	ing = ing.DeepCopy()
 
+	if !utils.IsGLBCIngress(ing) {
```
Comment (rramkumar1) [inline pkg/controller/controller.go]: Nit: Add a small comment here to please.

File: pkg/controller/controller.go [hunk 5]
```diff
@@ -586,3 +600,7 @@ func (lbc *LoadBalancerController) ToSvcPorts(ings *extensions.IngressList) []ut
 	}
 	return knownPorts
 }
+
+func (lbc *LoadBalancerController) runIngressGC(state *gcState) error {
```
Comment (rramkumar1) [inline pkg/controller/controller.go]: Now that I look at this, I realize we probably don't need a separate function for this. Just inline the call to GC()
