### PR TITLE
Fix BackendConfig.securityPolicy is not removed after config updates

### LINKED ISSUE #1706: BackendConfig.securityPolicy is not removed after config updates
I have the following _BackendConfig_ with _securityPolicy_ that applies rate limite on a public API we expose via google load balancers. 

```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/
    port: 80
  securityPolicy:
    name: rate-limit
```

The policy itself works fine to create the BackendConfig and update the Load Balancers with the desired policies, but it doesn't update ir accordingly when we remove the policy.

During releases, our team need to run performance tests against the APIs behind this policy to ensure it has not decreased performance, but unfortunatelly due to a bug in the `ingress-gce` we can't disable the policy after it is applied, causing our tests to be blocked.

I've investigated the [source code](https://github.com/kubernetes/ingress-gce/blob/37a3586364079f4af0726a0fc444135e42a56bf7/pkg/backends/features/securitypolicy.go#L35) and identified that it skips the policySetup when the `securityPolicy` is not defined.

In order to solve this issue, we need a way to either set the policy to `None` like in the ui, or it should check if a policy in the resource matches the one defined in the BackendConfig to remove it if they don't match.

### PR DESCRIPTION
**Pull request by songrx1997**
Fix [issue](https://github.com/kubernetes/ingress-gce/issues/1706) #1706 BackendConfig.securityPolicy is not removed after config updates

### CODE REVIEW

**Comment by swetharepakula** [comment]
Thanks for the change Ruixian! My main comment is that we want to still be able to exit early if we see that no change needs to be done for security policy. Can you also add a unit test for this change?

**Comment by songrx1997** [comment]
Hi @swetharepakula thanks for you comment.

> Thanks for the change Ruixian! My main comment is that we want to still be able to exit early if we see that no change needs to be done for security policy. 
For this, we need to know the desired security policy and current security policy. If they are different, we need to change the policy. Otherwise we do nothing and exit. So I think only after [getting both the desired and current policy](https://github.com/kubernetes/ingress-gce/pull/1749/commits/a5bbb02dc540961ab69644ff95c93e2ae43db789#diff-694a3074761a6ab43364827c08bb7533a5532940ce0c8a11c418f4ed266d9ce2R51) can we know whether changes need to be done. 

> Can you also add a unit test for this change?
Will do this, thanks for reminding!

**Comment by songrx1997** [comment]
Add a new [commit](https://github.com/kubernetes/ingress-gce/pull/1749/commits/143afcc0f94e36f0942e119c1aa511845365e59a) to update the test cases.

Added a new test case `remove-policy-2` for the situation:
Current Backend Service with securityPolicy &&  BackendConfig without securityPolicy ->  need to make a call to remove the policy. (This is the case in #1706 )

Removed `no-specified-policy`. We should make a call and remove the policy in this situation. So the case is no longer applicable.

File: pkg/backends/features/securitypolicy_test.go [hunk 1]
```diff
@@ -78,7 +78,7 @@ func TestEnsureSecurityPolicy(t *testing.T) {
 			expectSetCall: true,
 		},
 		{
-			desc: "remove-policy",
+			desc: "remove-policy-1",
```
Comment (swetharepakula) [inline pkg/backends/features/securitypolicy_test.go:81]: nit: maybe rename to `change-security-policy`

File: pkg/backends/features/securitypolicy_test.go [hunk 2]
```diff
@@ -92,6 +92,15 @@ func TestEnsureSecurityPolicy(t *testing.T) {
 			},
 			expectSetCall: true,
 		},
+		{
+			desc: "remove-policy-2",
```
Comment (swetharepakula) [inline pkg/backends/features/securitypolicy_test.go:96]: nit: rename to `remove-policy` or `unset-policy`

File: pkg/backends/features/securitypolicy_test.go [hunk 3]
```diff
@@ -111,15 +120,6 @@ func TestEnsureSecurityPolicy(t *testing.T) {
 			currentBackendService: &composite.BackendService{Scope: meta.Global},
 			desiredConfig:         &backendconfigv1.BackendConfig{},
 		},
-		{
-			desc: "no-specified-policy",
-			currentBackendService: &composite.BackendService{
-				Scope:          meta.Global,
-				SecurityPolicy: "https://www.googleapis.com/compute/projects/test-project/global/securityPolicies/policy-1",
```
Comment (swetharepakula) [inline pkg/backends/features/securitypolicy_test.go:118]: modify this test so that the SecurityPolicy is not set in the currentBackendService

**Review by swetharepakula — COMMENTED** [review]
Few nits left. This is almost ready to merge. Thanks!

File: pkg/backends/features/securitypolicy_test.go (hunk 1 above)
Comment (songrx1997) [reply pkg/backends/features/securitypolicy_test.go]: Thanks @swetharepakula , this case would unset the security policy since the name field in the config is an empty string. I think `unset-policy-empty-policy-string` would be more clear.

File: pkg/backends/features/securitypolicy_test.go (hunk 2 above)
Comment (songrx1997) [reply pkg/backends/features/securitypolicy_test.go]: Thanks @swetharepakula , this case would unset the security policy but it is different than the previous one. This one have no security policy field in the config. So I think `unset-policy-no-policy` would be more clear.

File: pkg/backends/features/securitypolicy_test.go (hunk 3 above)
Comment (songrx1997) [reply pkg/backends/features/securitypolicy_test.go:118]: Thanks @swetharepakula , this is the `unset-policy-no-policy` test. Since it is similar to `unset-policy-empty-policy-string`, I put them together to make it clear.

File: pkg/backends/features/securitypolicy.go [hunk 4]
```diff
@@ -31,20 +31,23 @@ import (
...
 func EnsureSecurityPolicy(cloud *gce.Cloud, sp utils.ServicePort, be *composite.BackendService) error {
-	if sp.BackendConfig.Spec.SecurityPolicy == nil {
-		return nil
-	}
-
 	if be.Scope != meta.Global {
 		return fmt.Errorf("cloud armor security policies not supported for %s backend service %s", be.Scope, be.Name)
 	}
 
+	var desiredPolicyName string
```
Comment (swetharepakula) [inline pkg/backends/features/securitypolicy.go:38]: @spencerhance, is there any problem because we are checking the scope before checking if security policy is nil? I am wondering if there are some cases where we will accidentally return an error but previously we would have moved on because security policy was nil?

File: pkg/backends/features/securitypolicy.go [hunk 5]
```diff
@@ -31,24 +31,27 @@ import (
...
-		return nil
-	}
-
-	if be.Scope != meta.Global {
-		return fmt.Errorf("cloud armor security policies not supported for %s backend service %s", be.Scope, be.Name)
+	var desiredPolicyName string
+	if sp.BackendConfig.Spec.SecurityPolicy != nil {
+		desiredPolicyName = sp.BackendConfig.Spec.SecurityPolicy.Name
+	} else {
+		desiredPolicyName = ""
```
Comment (spencerhance) [inline pkg/backends/features/securitypolicy.go:38]: desiredPolicyName should be an empty string by default right?

File: pkg/backends/features/securitypolicy.go (hunk 4 above)
Comment (spencerhance) [reply pkg/backends/features/securitypolicy.go:34]: Hm I think it should be okay because the policies would have to be different as well as the scope being regional.  Since you can't set the security policy on a regional BackendService I think we should be okay.

**Review by spencerhance — APPROVED** [review]
One possible scenario is that there is some customer who got stuck in this state accidentally and will be suprised when their policy is removed.  That being said, it's probably a very rare occurrence given how important securityPolicy is.

File: pkg/backends/features/securitypolicy.go (hunk 5 above)
Comment (songrx1997) [reply pkg/backends/features/securitypolicy.go:38]: Yes it should be an empty string.

**Comment by songrx1997** [comment]
> One possible scenario is that there is some customer who got stuck in this state accidentally and will be suprised when their policy is removed. That being said, it's probably a very rare occurrence given how important securityPolicy is.

Thanks @spencerhance Do you mean the situation that customers forget to put SecurityPolicy in the backendConfig and accidentally unset their security policy?

File: pkg/backends/features/securitypolicy.go (hunk 4 above)
Comment (swetharepakula) [reply pkg/backends/features/securitypolicy.go:34]: My comment isn't applicable anymore. The previous version checked the scope before checking if there was a change to the security policy. I think this version of the code doesn't run into the issue I mentioned above. Thanks for reviewing Spencer!

File: pkg/backends/features/securitypolicy_test.go (hunk 3 above)
Comment (swetharepakula) [reply pkg/backends/features/securitypolicy_test.go:118]: I think "regional backend service with no specified security policy" covers the case I was thinking of.

**Review by swetharepakula — COMMENTED** [review]
Thanks for the change Ruixian!

/lgtm
/approve
